from google.cloud import bigquery

ROYALLEPAGE_LOADJOBCONFIGS = {
    "listings": {
        "schema": [
            bigquery.SchemaField("listingDate", "STRING"),
            bigquery.SchemaField("openHouseAvailable", "BOOLEAN"),
            bigquery.SchemaField("provState", "STRING"),
            bigquery.SchemaField("city", "STRING"),
            bigquery.SchemaField("postalCode", "STRING"),
            bigquery.SchemaField("carriageTrade", "STRING"),
            bigquery.SchemaField(
                "searchListingType",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("bedsInt", "INTEGER"),
            bigquery.SchemaField("detailsPath", "STRING"),
            bigquery.SchemaField("leasePeriod", "STRING"),
            bigquery.SchemaField(
                "listingAgents",
                "STRING",
                mode="REPEATED",
            ),
            bigquery.SchemaField("listingPriceUOM", "STRING"),
            bigquery.SchemaField("neighbourhood", "STRING"),
            bigquery.SchemaField(
                "NBHDEnEntry",
                "RECORD",
                fields=[
                    bigquery.SchemaField("name", "STRING"),
                ],
            ),
            bigquery.SchemaField("price", "FLOAT"),
            bigquery.SchemaField("propertyType", "STRING"),
            bigquery.SchemaField("listingStatus", "STRING"),
            bigquery.SchemaField("lat", "FLOAT"),
            bigquery.SchemaField(
                "NBHDFrEntry",
                "RECORD",
                fields=[
                    bigquery.SchemaField("name", "STRING"),
                ],
            ),
            bigquery.SchemaField("lng", "FLOAT"),
            bigquery.SchemaField("searchType", "INTEGER"),
            bigquery.SchemaField("address2", "STRING"),
            bigquery.SchemaField("address1", "STRING"),
            bigquery.SchemaField("photo", "STRING"),
            bigquery.SchemaField("priceChanged", "BOOLEAN"),
            bigquery.SchemaField("taxExtra", "BOOLEAN"),
            bigquery.SchemaField("jumpId", "STRING"),
            bigquery.SchemaField(
                "liveStreams",
                "STRING",
                mode="REPEATED",
            ),
            bigquery.SchemaField("transactionType", "STRING"),
            bigquery.SchemaField("leasePriceUOM", "STRING"),
            bigquery.SchemaField("feed", "INTEGER"),
            bigquery.SchemaField("baths", "INTEGER"),
            bigquery.SchemaField("enhancedListing", "BOOLEAN"),
            bigquery.SchemaField("comingSoon", "BOOLEAN"),
            bigquery.SchemaField("displayAddress", "BOOLEAN"),
            bigquery.SchemaField("parent_id", "STRING", mode="REPEATED"),
            bigquery.SchemaField("recentlyCreated", "BOOLEAN"),
            bigquery.SchemaField("beds", "INTEGER"),
            bigquery.SchemaField("brokerName", "STRING"),
            bigquery.SchemaField(
                "searchPropertyType",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField(
                "extraInfo",
                "RECORD",
                fields=[
                    bigquery.SchemaField("listingTypeKey_en", "STRING"),
                    bigquery.SchemaField("listingTypeKey_fr", "STRING"),
                ],
            ),
            bigquery.SchemaField("bathsInt", "INTEGER"),
            bigquery.SchemaField("leasePrice", "FLOAT"),
            bigquery.SchemaField("sort", "STRING"),
            bigquery.SchemaField("listingFlagInd", "BOOLEAN"),
            bigquery.SchemaField("listingFlags", "STRING"),
            bigquery.SchemaField("listingFlagClasses", "STRING"),
            bigquery.SchemaField("listingStatusTrans", "STRING"),
            bigquery.SchemaField("dt", "DATE"),
        ],
        "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        "write_disposition": "WRITE_TRUNCATE",
    },
    "demographics": {
        "schema": [
            bigquery.SchemaField("life_stage", "STRING"),
            bigquery.SchemaField("employment_type", "STRING"),
            bigquery.SchemaField("average_household_income", "STRING"),
            bigquery.SchemaField("average_number_of_children", "STRING"),
            bigquery.SchemaField("no_certificate_diploma_degree", "STRING"),
            bigquery.SchemaField("high_school_certificate_or_equivalent", "STRING"),
            bigquery.SchemaField("apprenticeship_trade_certificate_diploma", "STRING"),
            bigquery.SchemaField("college_non_university_certificate", "STRING"),
            bigquery.SchemaField("university_certificate_below_bachelor", "STRING"),
            bigquery.SchemaField("university_degree", "STRING"),
            bigquery.SchemaField("by_car", "STRING"),
            bigquery.SchemaField("by_public_transit", "STRING"),
            bigquery.SchemaField("by_walking", "STRING"),
            bigquery.SchemaField("by_bicycle", "STRING"),
            bigquery.SchemaField("by_other_methods", "STRING"),
            bigquery.SchemaField("apartments_low_and_high_rise", "STRING"),
            bigquery.SchemaField("houses", "STRING"),
            bigquery.SchemaField("detailsPath", "STRING"),
            bigquery.SchemaField("dt", "DATE"),
        ],
        "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        "write_disposition": "WRITE_TRUNCATE",
    },
    "listing_details": {
        "commercial": {
            "schema": [
                bigquery.SchemaField("air_conditioning", "STRING"),
                bigquery.SchemaField("association_fee_includes", "STRING"),
                bigquery.SchemaField("built_in", "STRING"),
                bigquery.SchemaField("business_type", "STRING"),
                bigquery.SchemaField("construction_materials", "STRING"),
                bigquery.SchemaField("cooling", "STRING"),
                bigquery.SchemaField("cooling_type", "STRING"),
                bigquery.SchemaField("floor_space", "STRING"),
                bigquery.SchemaField("floor_space_approx", "STRING"),
                bigquery.SchemaField("foundation_details", "STRING"),
                bigquery.SchemaField("heating", "STRING"),
                bigquery.SchemaField("irregular", "STRING"),
                bigquery.SchemaField("lot_size", "STRING"),
                bigquery.SchemaField("property_access", "STRING"),
                bigquery.SchemaField("property_type", "STRING"),
                bigquery.SchemaField("roof", "STRING"),
                bigquery.SchemaField("sewer", "STRING"),
                bigquery.SchemaField("style", "STRING"),
                bigquery.SchemaField("total_finished_area", "STRING"),
                bigquery.SchemaField("utilities", "STRING"),
                bigquery.SchemaField("water_source", "STRING"),
                bigquery.SchemaField("zoning", "STRING"),
                bigquery.SchemaField("listingTypeKey_en", "STRING"),
                bigquery.SchemaField("detailsPath", "STRING"),
                bigquery.SchemaField("dt", "DATE"),
            ],
            "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            "write_disposition": "WRITE_TRUNCATE",
        },
        "condo": {
            "schema": [
                bigquery.SchemaField("air_conditioning", "STRING"),
                bigquery.SchemaField("amenities", "STRING"),
                bigquery.SchemaField("amenities_nearby", "STRING"),
                bigquery.SchemaField("appliances", "STRING"),
                bigquery.SchemaField("architectural_style", "STRING"),
                bigquery.SchemaField("association_fee_includes", "STRING"),
                bigquery.SchemaField("basement_development", "STRING"),
                bigquery.SchemaField("basement_type", "STRING"),
                bigquery.SchemaField("bathrooms", "STRING"),
                bigquery.SchemaField("bedrooms", "STRING"),
                bigquery.SchemaField("building_type", "STRING"),
                bigquery.SchemaField("built_in", "STRING"),
                bigquery.SchemaField("community_features", "STRING"),
                bigquery.SchemaField("condo_fees", "STRING"),
                bigquery.SchemaField("construction_material", "STRING"),
                bigquery.SchemaField("construction_materials", "STRING"),
                bigquery.SchemaField("construction_style___attachment", "STRING"),
                bigquery.SchemaField("cooling", "STRING"),
                bigquery.SchemaField("cooling_type", "STRING"),
                bigquery.SchemaField("exterior_features", "STRING"),
                bigquery.SchemaField("exterior_finish", "STRING"),
                bigquery.SchemaField("features", "STRING"),
                bigquery.SchemaField("fence_type", "STRING"),
                bigquery.SchemaField("fireplace", "STRING"),
                bigquery.SchemaField("fireplace_features", "STRING"),
                bigquery.SchemaField("floor_space", "STRING"),
                bigquery.SchemaField("floor_space_approx", "STRING"),
                bigquery.SchemaField("flooring", "STRING"),
                bigquery.SchemaField("flooring_type", "STRING"),
                bigquery.SchemaField("foundation_details", "STRING"),
                bigquery.SchemaField("foundation_type", "STRING"),
                bigquery.SchemaField("garage", "STRING"),
                bigquery.SchemaField("half_bathrooms", "STRING"),
                bigquery.SchemaField("heating", "STRING"),
                bigquery.SchemaField("heating_fuel", "STRING"),
                bigquery.SchemaField("heating_type", "STRING"),
                bigquery.SchemaField("interior_features", "STRING"),
                bigquery.SchemaField("irregular", "STRING"),
                bigquery.SchemaField("landscape_features", "STRING"),
                bigquery.SchemaField("levels", "STRING"),
                bigquery.SchemaField("lot_frontage", "STRING"),
                bigquery.SchemaField("lot_size", "STRING"),
                bigquery.SchemaField("maintenancefee_type", "STRING"),
                bigquery.SchemaField("no_of_parking_spaces", "STRING"),
                bigquery.SchemaField("ownershiptype", "STRING"),
                bigquery.SchemaField("parking_features", "STRING"),
                bigquery.SchemaField("parking_type", "STRING"),
                bigquery.SchemaField("pool", "STRING"),
                bigquery.SchemaField("property_access", "STRING"),
                bigquery.SchemaField("property_type", "STRING"),
                bigquery.SchemaField("roof", "STRING"),
                bigquery.SchemaField("sewer", "STRING"),
                bigquery.SchemaField("structure_type", "STRING"),
                bigquery.SchemaField("style", "STRING"),
                bigquery.SchemaField("total_finished_area", "STRING"),
                bigquery.SchemaField("utilities", "STRING"),
                bigquery.SchemaField("water_source", "STRING"),
                bigquery.SchemaField("waterfront_features", "STRING"),
                bigquery.SchemaField("zoning", "STRING"),
                bigquery.SchemaField("listingTypeKey_en", "STRING"),
                bigquery.SchemaField("detailsPath", "STRING"),
                bigquery.SchemaField("dt", "DATE"),
            ],
            "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            "write_disposition": "WRITE_TRUNCATE",
        },
        "house": {
            "schema": [
                bigquery.SchemaField("air_conditioning", "STRING"),
                bigquery.SchemaField("amenities_nearby", "STRING"),
                bigquery.SchemaField("applicances", "STRING"),
                bigquery.SchemaField("architectural_style", "STRING"),
                bigquery.SchemaField("association_fee_includes", "STRING"),
                bigquery.SchemaField("basement_development", "STRING"),
                bigquery.SchemaField("basement_type", "STRING"),
                bigquery.SchemaField("bathrooms", "STRING"),
                bigquery.SchemaField("bedrooms", "STRING"),
                bigquery.SchemaField("building_type", "STRING"),
                bigquery.SchemaField("built_in", "STRING"),
                bigquery.SchemaField("construction_material", "STRING"),
                bigquery.SchemaField("construction_materials", "STRING"),
                bigquery.SchemaField("construction_style___attachment", "STRING"),
                bigquery.SchemaField("cooling", "STRING"),
                bigquery.SchemaField("cooling_type", "STRING"),
                bigquery.SchemaField("exterior_features", "STRING"),
                bigquery.SchemaField("exterior_finish", "STRING"),
                bigquery.SchemaField("features", "STRING"),
                bigquery.SchemaField("fence_type", "STRING"),
                bigquery.SchemaField("fireplace", "STRING"),
                bigquery.SchemaField("fireplace_features", "STRING"),
                bigquery.SchemaField("floor_space", "STRING"),
                bigquery.SchemaField("floor_space_approx", "STRING"),
                bigquery.SchemaField("flooring", "STRING"),
                bigquery.SchemaField("flooring_type", "STRING"),
                bigquery.SchemaField("foundation_details", "STRING"),
                bigquery.SchemaField("foundation_type", "STRING"),
                bigquery.SchemaField("garage", "STRING"),
                bigquery.SchemaField("half_bathrooms", "STRING"),
                bigquery.SchemaField("heating", "STRING"),
                bigquery.SchemaField("heating_fuel", "STRING"),
                bigquery.SchemaField("heating_type", "STRING"),
                bigquery.SchemaField("interior_features", "STRING"),
                bigquery.SchemaField("irregular", "STRING"),
                bigquery.SchemaField("landscape_features", "STRING"),
                bigquery.SchemaField("levels", "STRING"),
                bigquery.SchemaField("lot_depth", "STRING"),
                bigquery.SchemaField("lot_frontage", "STRING"),
                bigquery.SchemaField("lot_size", "STRING"),
                bigquery.SchemaField("no_of_parking_spaces", "STRING"),
                bigquery.SchemaField("ownershiptype", "STRING"),
                bigquery.SchemaField("parking_features", "STRING"),
                bigquery.SchemaField("parking_type", "STRING"),
                bigquery.SchemaField("pool", "STRING"),
                bigquery.SchemaField("property_type", "STRING"),
                bigquery.SchemaField("roof", "STRING"),
                bigquery.SchemaField("sewer", "STRING"),
                bigquery.SchemaField("structure_type", "STRING"),
                bigquery.SchemaField("style", "STRING"),
                bigquery.SchemaField("total_finished_area", "STRING"),
                bigquery.SchemaField("utilities", "STRING"),
                bigquery.SchemaField("water_source", "STRING"),
                bigquery.SchemaField("waterfront_features", "STRING"),
                bigquery.SchemaField("zoning", "STRING"),
                bigquery.SchemaField("listingTypeKey_en", "STRING"),
                bigquery.SchemaField("detailsPath", "STRING"),
                bigquery.SchemaField("dt", "DATE"),
            ],
            "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            "write_disposition": "WRITE_TRUNCATE",
        },
        "investment": {
            "schema": [
                bigquery.SchemaField("air_conditioning", "STRING"),
                bigquery.SchemaField("architectural_style", "STRING"),
                bigquery.SchemaField("bathrooms", "STRING"),
                bigquery.SchemaField("bedrooms", "STRING"),
                bigquery.SchemaField("built_in", "STRING"),
                bigquery.SchemaField("construction_materials", "STRING"),
                bigquery.SchemaField("cooling", "STRING"),
                bigquery.SchemaField("deck", "STRING"),
                bigquery.SchemaField("exterior_features", "STRING"),
                bigquery.SchemaField("fireplace_features", "STRING"),
                bigquery.SchemaField("floor_space_approx", "STRING"),
                bigquery.SchemaField("flooring", "STRING"),
                bigquery.SchemaField("foundation_details", "STRING"),
                bigquery.SchemaField("heating", "STRING"),
                bigquery.SchemaField("interior_features", "STRING"),
                bigquery.SchemaField("irregular", "STRING"),
                bigquery.SchemaField("levels", "STRING"),
                bigquery.SchemaField("lot_size", "STRING"),
                bigquery.SchemaField("master_bedroom_on_main_floor", "STRING"),
                bigquery.SchemaField("new_construction", "STRING"),
                bigquery.SchemaField("parking_features", "STRING"),
                bigquery.SchemaField("pets_allowed", "STRING"),
                bigquery.SchemaField("property_access", "STRING"),
                bigquery.SchemaField("roof", "STRING"),
                bigquery.SchemaField("sewer", "STRING"),
                bigquery.SchemaField("total_finished_area", "STRING"),
                bigquery.SchemaField("utilities", "STRING"),
                bigquery.SchemaField("water_source", "STRING"),
                bigquery.SchemaField("zoning", "STRING"),
                bigquery.SchemaField("listingTypeKey_en", "STRING"),
                bigquery.SchemaField("detailsPath", "STRING"),
                bigquery.SchemaField("dt", "DATE"),
            ],
            "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            "write_disposition": "WRITE_TRUNCATE",
        },
        "vacant_land": {
            "schema": [
                bigquery.SchemaField("bathrooms", "STRING"),
                bigquery.SchemaField("bedrooms", "STRING"),
                bigquery.SchemaField("hoa", "STRING"),
                bigquery.SchemaField("irregular", "STRING"),
                bigquery.SchemaField("lot_size", "STRING"),
                bigquery.SchemaField("property_access", "STRING"),
                bigquery.SchemaField("sewer", "STRING"),
                bigquery.SchemaField("utilities", "STRING"),
                bigquery.SchemaField("water_source", "STRING"),
                bigquery.SchemaField("waterfront_features", "STRING"),
                bigquery.SchemaField("zoning", "STRING"),
                bigquery.SchemaField("listingTypeKey_en", "STRING"),
                bigquery.SchemaField("detailsPath", "STRING"),
                bigquery.SchemaField("dt", "DATE"),
            ],
            "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
            "write_disposition": "WRITE_TRUNCATE",
        },
    },
    "lifestyle_scores": {
        "schema": [
            bigquery.SchemaField(
                "data",
                "RECORD",
                fields=[
                    bigquery.SchemaField("type", "STRING"),
                    bigquery.SchemaField(
                        "attributes",
                        "RECORD",
                        fields=[
                            bigquery.SchemaField(
                                "high_schools",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "primary_schools",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "transit_friendly",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "groceries",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "restaurants",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "pedestrian_friendly",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "cycling_friendly",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "car_friendly",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "vibrant",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "shopping",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "daycares",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "nightlife",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "cafes",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "quiet",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                            bigquery.SchemaField(
                                "parks",
                                "RECORD",
                                fields=[
                                    bigquery.SchemaField("value", "FLOAT"),
                                    bigquery.SchemaField("text", "STRING"),
                                    bigquery.SchemaField("category", "STRING"),
                                ],
                            ),
                        ],
                    ),
                    bigquery.SchemaField(
                        "links",
                        "RECORD",
                        fields=[
                            bigquery.SchemaField("nearby", "STRING"),
                            bigquery.SchemaField("around", "STRING"),
                        ],
                    ),
                ],
            ),
            bigquery.SchemaField(
                "meta",
                "RECORD",
                fields=[
                    bigquery.SchemaField(
                        "around",
                        "STRING",
                        mode="REPEATED",
                    ),
                    bigquery.SchemaField("sid", "STRING"),
                    bigquery.SchemaField("version", "STRING"),
                ],
            ),
            bigquery.SchemaField("detailsPath", "STRING"),
            bigquery.SchemaField("dt", "DATE"),
        ],
        "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        "write_disposition": "WRITE_TRUNCATE",
    },
}
