from google.cloud import bigquery

LOCATION_SCORE_FIELDS = [
    bigquery.SchemaField("category", "STRING"),
    bigquery.SchemaField("name", "STRING"),
    bigquery.SchemaField("text", "STRING"),
    bigquery.SchemaField("value", "STRING"),
    bigquery.SchemaField("display_name", "STRING"),
]

ZUMPER_LOADJOBCONFIGS = {
    "listables": {
        "schema": [
            bigquery.SchemaField("pa_should_index", "BOOLEAN"),
            bigquery.SchemaField("listing_id", "INTEGER"),
            bigquery.SchemaField("created_on", "INTEGER"),
            bigquery.SchemaField("modified_on", "INTEGER"),
            bigquery.SchemaField("listed_on", "INTEGER"),
            bigquery.SchemaField("listing_status", "INTEGER"),
            bigquery.SchemaField("group_id", "INTEGER"),
            bigquery.SchemaField("address", "STRING"),
            bigquery.SchemaField("city", "STRING"),
            bigquery.SchemaField("lat", "FLOAT"),
            bigquery.SchemaField("lng", "FLOAT"),
            bigquery.SchemaField(
                "pets",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("leasing_fee", "FLOAT"),
            bigquery.SchemaField("building_id", "INTEGER"),
            bigquery.SchemaField("feed_name", "STRING"),
            bigquery.SchemaField(
                "image_ids",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("neighborhood_id", "INTEGER"),
            bigquery.SchemaField("neighborhood_name", "STRING"),
            bigquery.SchemaField("brokerage_id", "INTEGER"),
            bigquery.SchemaField("agent_id", "INTEGER"),
            bigquery.SchemaField("agent_name", "STRING"),
            bigquery.SchemaField("brokerage_name", "STRING"),
            bigquery.SchemaField("brokerage_homepage", "STRING"),
            bigquery.SchemaField("state", "STRING"),
            bigquery.SchemaField("building_name", "STRING"),
            bigquery.SchemaField("viewings", "INTEGER"),
            bigquery.SchemaField("tz", "STRING"),
            bigquery.SchemaField("is_messageable", "BOOLEAN"),
            bigquery.SchemaField("city_state", "STRING"),
            bigquery.SchemaField("zappable", "INTEGER"),
            bigquery.SchemaField("property_type", "INTEGER"),
            bigquery.SchemaField(
                "amenities",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField(
                "building_amenities",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("phone", "STRING"),
            bigquery.SchemaField("listing_type", "INTEGER"),
            bigquery.SchemaField("pb_id", "INTEGER"),
            bigquery.SchemaField("pb_url", "STRING"),
            bigquery.SchemaField("date_available", "STRING"),
            bigquery.SchemaField("max_price", "INTEGER"),
            bigquery.SchemaField("min_price", "INTEGER"),
            bigquery.SchemaField("max_bedrooms", "INTEGER"),
            bigquery.SchemaField("min_bedrooms", "INTEGER"),
            bigquery.SchemaField("max_bathrooms", "INTEGER"),
            bigquery.SchemaField("min_bathrooms", "INTEGER"),
            bigquery.SchemaField("floorplan_count", "INTEGER"),
            bigquery.SchemaField("min_lease_days", "INTEGER"),
            bigquery.SchemaField("max_lease_days", "INTEGER"),
            bigquery.SchemaField("lease_type", "INTEGER"),
            bigquery.SchemaField(
                "features",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("zipcode", "STRING"),
            bigquery.SchemaField("is_pad", "BOOLEAN"),
            bigquery.SchemaField("short_description", "STRING"),
            bigquery.SchemaField(
                "amenity_tags",
                "STRING",
                mode="REPEATED",
            ),
            bigquery.SchemaField(
                "building_amenity_tags",
                "STRING",
                mode="REPEATED",
            ),
            bigquery.SchemaField(
                "max_all_bathrooms",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField(
                "min_all_bathrooms",
                "INTEGER",
                mode="REPEATED",
            ),
            bigquery.SchemaField("pl_id", "INTEGER"),
            bigquery.SchemaField("pl_url", "STRING"),
            bigquery.SchemaField("pa_url", "STRING"),
            bigquery.SchemaField("amenity_json", "STRING"),
            bigquery.SchemaField("pet_policy_json", "STRING"),
            bigquery.SchemaField("max_adults", "INTEGER"),
            bigquery.SchemaField("max_children", "INTEGER"),
            bigquery.SchemaField("title", "STRING"),
            bigquery.SchemaField("is_filter_ad", "BOOLEAN"),
            bigquery.SchemaField("provider_url", "STRING"),
            bigquery.SchemaField("rating", "INTEGER"),
            bigquery.SchemaField("url", "STRING"),
            bigquery.SchemaField("neighborhood_url", "STRING"),
            bigquery.SchemaField("external", "INTEGER"),
            bigquery.SchemaField("promotion_type", "INTEGER"),
            bigquery.SchemaField("dt", "DATE"),
        ],
        "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        "write_disposition": "WRITE_TRUNCATE",
    },
    "location_scores": {
        "schema": [
            bigquery.SchemaField("location_scores_id", "INTEGER"),
            bigquery.SchemaField("created_on", "INTEGER"),
            bigquery.SchemaField("modified_on", "INTEGER"),
            bigquery.SchemaField(
                "scores_json",
                "RECORD",
                fields=[
                    bigquery.SchemaField(
                        "cafes",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "parks",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "quiet",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "vibrant",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "daycares",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "shopping",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "groceries",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "nightlife",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "restaurants",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "car_friendly",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "high_schools",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "primary_schools",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "cycling_friendly",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "transit_friendly",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                    bigquery.SchemaField(
                        "pedestrian_friendly",
                        "RECORD",
                        fields=LOCATION_SCORE_FIELDS,
                    ),
                ],
            ),
            bigquery.SchemaField("reduced_lat", "INTEGER"),
            bigquery.SchemaField("reduced_lng", "INTEGER"),
            bigquery.SchemaField("group_id", "INTEGER"),
            bigquery.SchemaField("initial_lat", "FLOAT"),
            bigquery.SchemaField("initial_lng", "FLOAT"),
            bigquery.SchemaField("city_state", "STRING"),
            bigquery.SchemaField("neighborhood_id", "INTEGER"),
            bigquery.SchemaField("zipcode", "STRING"),
            bigquery.SchemaField("state", "STRING"),
            bigquery.SchemaField("country_id", "STRING"),
            bigquery.SchemaField("listing_id", "INTEGER"),
            bigquery.SchemaField("dt", "DATE"),
        ],
        "source_format": bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
        "write_disposition": "WRITE_TRUNCATE",
    },
}
